"""
This plugin automatically builds nedoc documentation during a mkdocs build.
It also allows you to use links to API documentation of a Python package documented by Nedoc.

Use a link with text wrapped by backticks (`) and set the link URL to a key contained in `map.json`.
`map.json` is generated by Nedoc if you use the `create_map_json = True` configuration in `nedoc.conf`.

Links cannot span a line! Keep them on a single line.
Links that start with # will not be considered.

Example:
The [`Box`](elsie.box.Box) class is awesome.
"""
import json
import logging
import os
import re
from pathlib import Path

import mkdocs
import nedoc.config
from mkdocs.plugins import BasePlugin
from nedoc import core

# The second group is used to avoid adding the hash fragment to the link lookup key
LINK_REGEX = re.compile(r"\[`.*?`]\(((?!#)[^#]*?)(#.*?)?\)")


def load_nedoc_config(config) -> nedoc.config.Config:
    docs_dir = Path(config["docs_dir"])
    root_dir = docs_dir.parent
    conf_file = root_dir / "nedoc.conf"
    if not conf_file.exists():
        raise Exception(f"nedoc configuration file {conf_file} does not exist. Run `nedoc "
                        "init`.")
    return nedoc.config.parse_config(str(conf_file))


def build_nedoc(config: nedoc.config.Config, target_dir: Path):
    config.target_path = str(target_dir)

    c = core.Core(config)
    c.build()


class NedocPlugin(BasePlugin):
    """
    This plugin automatically builds nedoc documentation during mkdocs build and also provides
    links into the API documentation from Markdown.
    """
    config_scheme = (
        ("path", mkdocs.config.config_options.Type(str, default="apidoc")),
    )

    def __init__(self):
        self.site_url = None
        self.url_map = {}
        self.api_links = 0
        self.doc_path = None

    def on_config(self, config, **kwargs):
        # Normalize API site url
        self.doc_path = self.config["path"]

        self.site_url = config.get("site_url") or "/"
        if self.site_url and self.site_url[-1] != "/":
            self.site_url = f"{self.site_url}/"
        self.site_url = f"{self.site_url}{self.doc_path}"

    def on_files(self, files, config, **kwargs):
        # Build API documentation
        nedoc_config = load_nedoc_config(config)

        build_dir = Path(config["site_dir"])
        target_dir = build_dir / self.doc_path

        os.makedirs(target_dir, exist_ok=True)
        build_nedoc(nedoc_config, target_dir)

        print(f"Generated API documentation into {target_dir}, it will be available at "
              f"{self.site_url}")

        # Load URL map
        map_file = target_dir / "map.json"

        if os.path.isfile(map_file):
            with open(map_file) as f:
                self.url_map = json.load(f)
        else:
            logging.warning(f"WARNING: {map_file} file is missing")

    def on_page_markdown(self, src: str, page, config, *args, **kwargs):
        # TODO: use Markdown parser
        lines = []
        for (line_index, line) in enumerate(src.splitlines(keepends=False)):
            # Iterate from the end to make replacing substrings easier
            for match in reversed(list(LINK_REGEX.finditer(line))):
                link_key = match.group(1)
                link_url = self.url_map.get(link_key)
                if link_url:
                    self.api_links += 1
                    url = f"{self.site_url}/{link_url}"
                    start, end = match.span(1)
                    line = line[:start] + url + line[end:]
                else:
                    raise Exception(f"Link key {link_key} not found in {page.file.src_path} on "
                                    f"line {line_index}")
            lines.append(line)
        return "\n".join(lines)

    def on_post_build(self, config, **kwargs):
        print(f"Found {self.api_links} API links")

    def on_serve(self, server, config, builder, **kwargs):
        nedoc_config = load_nedoc_config(config)
        server.watch(nedoc_config.source_path, builder)
        return server
